from fpdf import FPDF

pdf = FPDF()
pdf.add_page()
pdf.set_font('Arial', 'B', 16)
pdf.cell(0, 10, 'John Doe', ln=True)
pdf.set_font('Arial', '', 12)
pdf.cell(0, 8, 'Software Engineer', ln=True)
pdf.ln(6)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Education', ln=True)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 7, 'Bachelor of Science in Computer Science, Example University, 2020')
pdf.ln(4)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Skills', ln=True)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 7, 'Python, TypeScript, Node.js, SQL, React')
pdf.ln(4)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Experience', ln=True)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 7, 'Software Engineer at Example Corp (2021-2024)\n- Built backend services and automation tools')
pdf.ln(4)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Projects', ln=True)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 7, 'Resume Parser Prototype\n- Created file upload and extraction pipeline')
pdf.ln(4)
pdf.set_font('Arial', 'B', 12)
pdf.cell(0, 8, 'Certifications', ln=True)
pdf.set_font('Arial', '', 12)
pdf.multi_cell(0, 7, 'Certified Kubernetes Administrator')
pdf.output('sample_resume_real.pdf')
print('created sample_resume_real.pdf')
